"""Build the v1 manuscript tables as LaTeX fragments from stored Phase 2 results.

Inputs (all produced by earlier, fixed scripts; nothing is fitted here):
    results/phase2-nominal-fpr/nominal-fpr-cells.csv        A1/A2 nominal-threshold cells
    results/phase2-human-null/human-vs-model-cells.csv      A6 human vs model cells
    results/phase2-confirmatory-null/failure-diagnosis.json A7 calibrated 60-cell record
Outputs:
    paper/arxiv/tables/table1-nominal-fpr.tex       Table 1: KGW nominal 1% FPR, 30 cells, n = 10,000
    paper/arxiv/tables/table2-human-null.tex        Table 2: human vs model FPR and p_k per key
    paper/arxiv/tables/tableA1-calibrated-cells.tex Table A1: 60 calibrated cells, held-out FPR with CIs
    paper/phase2-appendix-table-a1.md               Markdown twin of Table A1
    results/phase2-confirmatory-null/heldout-summary.json  numbers quoted in the C4 paragraph

Usage (repo root): python validation/build_phase2_v1_latex_tables.py
"""

from __future__ import annotations

import json
import os

import pandas as pd
from scipy import stats

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLES = os.path.join(ROOT, "paper", "arxiv", "tables")
LENGTHS = (128, 256, 512)


def cp(x: int, n: int, conf: float = 0.95) -> tuple[float, float]:
    a = 1 - conf
    lo = 0.0 if x == 0 else stats.beta.ppf(a / 2, x, n - x + 1)
    hi = 1.0 if x == n else stats.beta.ppf(1 - a / 2, x + 1, n - x)
    return float(lo), float(hi)


def pct_ci(p: float, lo: float, hi: float, d: int = 2) -> str:
    return f"{p*100:.{d}f} [{lo*100:.{d}f}, {hi*100:.{d}f}]"


def write(path: str, lines: list[str]) -> None:
    with open(path, "w") as f:
        f.write("% generated by validation/build_phase2_v1_latex_tables.py; do not edit\n")
        f.write("\n".join(lines) + "\n")


def table1(cells: pd.DataFrame) -> None:
    c = cells[(cells.run == "smollm2_n10000") & (cells.scheme == "kgw")]
    lines = [r"\begin{tabular}{lrrr}", r"\toprule",
             r"Key & 128 tokens & 256 tokens & 512 tokens \\", r"\midrule"]
    for key in sorted(c.key_id.unique()):
        vals = []
        for L in LENGTHS:
            r = c[(c.key_id == key) & (c.length == L)].iloc[0]
            vals.append(pct_ci(r.fpr, r.ci_lo, r.ci_hi))
        lines.append(f"{key} & " + " & ".join(vals) + r" \\")
    med = [c[c.length == L].fpr.median() for L in LENGTHS]
    lines += [r"\midrule", "Median & " + " & ".join(f"{m*100:.2f}" for m in med) + r" \\",
              r"\bottomrule", r"\end{tabular}"]
    write(os.path.join(TABLES, "table1-nominal-fpr.tex"), lines)


def table2(c: pd.DataFrame) -> None:
    lines = [r"\begin{tabular}{lrrrrrr}", r"\toprule",
             r"& \multicolumn{2}{c}{128 tokens} & \multicolumn{2}{c}{256 tokens} & \multicolumn{2}{c}{512 tokens} \\",
             r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
             r"Key & Human & Model & Human & Model & Human & Model \\", r"\midrule"]
    keys = sorted(c.key_id.unique())
    n_h = {L: int(c[(c.population == "human") & (c.length == L)].n.iloc[0]) for L in LENGTHS}
    for key in keys:
        vals = []
        for L in LENGTHS:
            for pop in ("human", "model"):
                r = c[(c.population == pop) & (c.length == L) & (c.key_id == key)].iloc[0]
                vals.append(f"{r.fpr*100:.1f}")
        lines.append(f"{key} & " + " & ".join(vals) + r" \\")
    lines.append(r"\midrule")
    lines.append(r"$p_k$ range & " + " & ".join(
        f"{c[(c.population == pop) & (c.length == L)].p_k.min():.3f}--{c[(c.population == pop) & (c.length == L)].p_k.max():.3f}"
        for L in LENGTHS for pop in ("human", "model")) + r" \\")
    lines.append("$n$ & " + " & ".join(
        f"{n_h[L]:,}" if pop == "human" else "10,000" for L in LENGTHS for pop in ("human", "model")) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(os.path.join(TABLES, "table2-human-null.tex"), lines)


def table_a1(diag: dict) -> dict:
    rows = []
    for cell in diag["cells"]:
        n = 5000
        x = int(cell["confirmation_exceedances"])
        lo, hi = cp(x, n)
        rows.append({"scheme": cell["scheme"], "key_id": cell["key_id"], "length": int(cell["length"]),
                     "threshold": float(cell["threshold"]),
                     "calibration_exceedances": int(cell["calibration_exceedances"]),
                     "confirmation_exceedances": x, "heldout_fpr": x / n, "ci_lo": lo, "ci_hi": hi,
                     "exact_upper_bound": float(cell["exact_upper_bound"]), "passed": bool(cell["passed"])})
    df = pd.DataFrame(rows).sort_values(["scheme", "key_id", "length"]).reset_index(drop=True)
    assert len(df) == 60

    # LaTeX: one table per scheme, 30 rows each
    lines = []
    for scheme, title in (("kgw", "Canonical KGW SelfHash (thresholds indexed by key and length)"),
                          ("synthid", "Canonical SynthID-Text (one shared threshold per length)")):
        d = df[df.scheme == scheme]
        lines += [r"\begin{table}[H]", r"\centering", r"\footnotesize",
                  rf"\caption{{{title}. Held-out false-positive rate of the once-fitted "
                  r"threshold on the 5,000-output confirmation split, with exact two-sided 95\% "
                  r"Clopper--Pearson intervals. Calib.\ and Conf.\ are strict exceedance counts on "
                  r"the calibration and confirmation splits; the Bonferroni-controlled one-sided "
                  r"exact upper bound had to be at most 1\% (28 exceedances) for the cell to pass.}",
                  rf"\label{{tab:a1-{scheme}}}",
                  r"\begin{tabular}{llrrrrrc}", r"\toprule",
                  r"Key & $T$ & Threshold & Calib. & Conf. & Held-out FPR (\%) [95\% CI] & Upper bound (\%) & Pass \\",
                  r"\midrule"]
        for _, r in d.iterrows():
            lines.append(f"{r.key_id} & {r.length} & {r.threshold:.4f} & {r.calibration_exceedances} & "
                         f"{r.confirmation_exceedances} & {pct_ci(r.heldout_fpr, r.ci_lo, r.ci_hi)} & "
                         f"{r.exact_upper_bound*100:.2f} & {'yes' if r.passed else 'no'}" + r" \\")
        lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}", ""]
    write(os.path.join(TABLES, "tableA1-calibrated-cells.tex"), lines)

    # Markdown twin
    md = ["# Appendix Table A1: calibrated per-cell held-out false-positive rates (generated)\n",
          "Source: `validation/build_phase2_v1_latex_tables.py` from",
          "`results/phase2-confirmatory-null/failure-diagnosis.json`. Thresholds were fitted once",
          "on the 5,000-output calibration split and evaluated once on the disjoint 5,000-output",
          "confirmation split. Held-out FPR is the confirmation strict-exceedance rate with exact",
          "two-sided 95% Clopper-Pearson intervals. Upper bound is the one-sided exact bound at",
          "alpha = 0.05/60; a cell passed if it was at most 1% (28 exceedances).\n",
          "| Scheme | Key | T | Threshold | Calib. exc. | Conf. exc. | Held-out FPR [95% CI] | Upper bound | Pass |",
          "|---|---|---:|---:|---:|---:|---:|---:|:---:|"]
    for _, r in df.iterrows():
        md.append(f"| {r.scheme} | {r.key_id} | {r.length} | {r.threshold:.4f} | {r.calibration_exceedances} | "
                  f"{r.confirmation_exceedances} | {r.heldout_fpr*100:.2f}% [{r.ci_lo*100:.2f}, {r.ci_hi*100:.2f}] | "
                  f"{r.exact_upper_bound*100:.2f}% | {'yes' if r.passed else 'no'} |")
    with open(os.path.join(ROOT, "paper", "phase2-appendix-table-a1.md"), "w") as f:
        f.write("\n".join(md) + "\n")

    summary = {
        "cells": 60,
        "passed": int(df.passed.sum()),
        "heldout_fpr_range": [float(df.heldout_fpr.min()), float(df.heldout_fpr.max())],
        "heldout_fpr_range_kgw": [float(df[df.scheme == "kgw"].heldout_fpr.min()), float(df[df.scheme == "kgw"].heldout_fpr.max())],
        "heldout_fpr_range_synthid": [float(df[df.scheme == "synthid"].heldout_fpr.min()), float(df[df.scheme == "synthid"].heldout_fpr.max())],
        "cells_ci_upper_above_1pct_two_sided": int((df.ci_hi > 0.01).sum()),
        "cells_point_above_1pct": int((df.heldout_fpr > 0.01).sum()),
        "max_ci_upper": float(df.ci_hi.max()),
        "kgw_calibration_cells_at_boundary_28": int((df[df.scheme == "kgw"].calibration_exceedances == 28).sum()),
        "mean_calibration_exceedances_kgw": float(df[df.scheme == "kgw"].calibration_exceedances.mean()),
        "mean_confirmation_exceedances_kgw": float(df[df.scheme == "kgw"].confirmation_exceedances.mean()),
        "worst_cell": df.loc[df.heldout_fpr.idxmax(), ["scheme", "key_id", "length", "heldout_fpr", "ci_lo", "ci_hi"]].to_dict(),
        "kgw07_512_threshold": float(df[(df.key_id == "kgw-07") & (df.length == 512)].threshold.iloc[0]),
        "kgw03_512_threshold": float(df[(df.key_id == "kgw-03") & (df.length == 512)].threshold.iloc[0]),
        "kgw_threshold_range_512": [float(df[(df.scheme == "kgw") & (df.length == 512)].threshold.min()),
                                    float(df[(df.scheme == "kgw") & (df.length == 512)].threshold.max())],
    }
    with open(os.path.join(ROOT, "results", "phase2-confirmatory-null", "heldout-summary.json"), "w") as f:
        json.dump(summary, f, indent=2)
    return summary


def main() -> int:
    os.makedirs(TABLES, exist_ok=True)
    cells = pd.read_csv(os.path.join(ROOT, "results", "phase2-nominal-fpr", "nominal-fpr-cells.csv"))
    table1(cells)
    human = pd.read_csv(os.path.join(ROOT, "results", "phase2-human-null", "human-vs-model-cells.csv"))
    table2(human)
    diag = json.load(open(os.path.join(ROOT, "results", "phase2-confirmatory-null", "failure-diagnosis.json")))
    summary = table_a1(diag)
    print(json.dumps(summary, indent=1))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
